# Centralisation des noms d'acteurs pour éviter les typos

ACTOR_FARMER = 'KODJO_MENSAH'
ACTOR_COOPERATIVE = 'COOPERATIVE_HAHO_UNION'
ACTOR_CCFCC = 'CCFCC'
ACTOR_EXPORTER = 'CACAO_TOGO_SARL'
ACTOR_OTR = 'OTR'
ACTOR_IMPORTER_EU = 'BIOEUROPE'

