# Generated by Django 6.0.5 on 2026-05-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(max_length=50, unique=True)),
                ('weight_declared', models.FloatField()),
                ('weight_verified', models.FloatField(blank=True, null=True)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('culture_type', models.CharField(choices=[('cacao', 'Cacao'), ('cafe', 'Café')], default='cacao', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lots/')),
                ('status', models.CharField(choices=[('REGISTERED', 'Enregistré'), ('IN_TRANSFER', 'En transit'), ('VALIDATED', 'Validé'), ('FRAUD_ALERT', 'Alerte fraude'), ('EXPORTED', 'Exporté'), ('CERTIFIED', 'Certifié')], default='REGISTERED', max_length=20)),
                ('blockchain_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('fraud_alert', models.BooleanField(default=False)),
                ('fraud_details', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='farmers.cooperative')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='farmers.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(max_length=100, unique=True)),
                ('cert_type', models.CharField(choices=[('EUDR', 'EUDR'), ('FAIRTRADE', 'Fairtrade'), ('BIO', 'Bio'), ('RAINFOREST', 'Rainforest Alliance')], max_length=20)),
                ('issued_by', models.CharField(max_length=200)),
                ('total_weight', models.FloatField()),
                ('blockchain_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('lots', models.ManyToManyField(related_name='certificates', to='lots.lot')),
            ],
        ),
        migrations.CreateModel(
            name='LotTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_actor', models.CharField(max_length=100)),
                ('to_actor', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='lots.lot')),
            ],
        ),
    ]
