# Generated by Django 6.0.5 on 2026-05-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_quality_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='humidity_percent',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='quality_observation',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='recent_treatments',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='rot_rate_percent',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='sanitary_status',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='visual_observation',
        ),
    ]
