# Generated by Django 6.0.5 on 2026-05-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_remove_lot_humidity_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='humidity_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='quality_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='recent_treatments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='rot_rate_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='sanitary_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='visual_observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
